[pytest]
testpaths = tests
log_cli = true
log_cli_level = INFO
log_format = %(message)s
markers =
    movies: тесты эндпоинтов работы с фильмами (/movies)
    api: автотесты API уровня
    smoke: дымовые тесты проверки критической функциональности
    regression: регрессионные тесты